name: Hawkeye Check

on:
  push: {}

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    container:
      # This tells GitHub Actions to use our docker image
      image: hawkeyesec/scanner-cli:latest
      # This tells GitHub Actions to mount the location where the code was checked out to /target
      options: -v /__w/as101-4-workshop/as101-4-workshop:/target
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: hawkeye scan
        run: |
          hawkeye scan --target web/
          
